name: Linters

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, synchronize, reopened]

jobs:
  codestyle-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run tsc:check

      - name: Check code style
        run: |
          npm run lint:ts
          npm run lint:editorconfig

      - name: Check tests
        run: npm run test

  codestyle-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check types
        run: npm run tsc:check

      - name: Check code style
        run: |
          npm run lint:ts
          npm run lint:css
          npm run lint:editorconfig

      - name: Check tests
        run: npm run test
